// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5qYCU6DkT-f7AvpfJ5cN-C4PkfhS2L8',
    appId: '1:391537771786:web:8b2318b49df5996bf426f3',
    messagingSenderId: '391537771786',
    projectId: 'has-gel-project',
    authDomain: 'has-gel-project.firebaseapp.com',
    storageBucket: 'has-gel-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB83N07mYcO7r9aTfSpuXrCDKi_SESvPMs',
    appId: '1:391537771786:android:2e7be133e999b524f426f3',
    messagingSenderId: '391537771786',
    projectId: 'has-gel-project',
    storageBucket: 'has-gel-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzMPhWh-h0Z50sTJjOdvm5ZDbPu5wTy4',
    appId: '1:391537771786:ios:13d5345c5108cfcef426f3',
    messagingSenderId: '391537771786',
    projectId: 'has-gel-project',
    storageBucket: 'has-gel-project.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzMPhWh-h0Z50sTJjOdvm5ZDbPu5wTy4',
    appId: '1:391537771786:ios:13d5345c5108cfcef426f3',
    messagingSenderId: '391537771786',
    projectId: 'has-gel-project',
    storageBucket: 'has-gel-project.firebasestorage.app',
    iosBundleId: 'com.example.prova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH5qYCU6DkT-f7AvpfJ5cN-C4PkfhS2L8',
    appId: '1:391537771786:web:3817cf96439ecdddf426f3',
    messagingSenderId: '391537771786',
    projectId: 'has-gel-project',
    authDomain: 'has-gel-project.firebaseapp.com',
    storageBucket: 'has-gel-project.firebasestorage.app',
  );

}